x = int(input("skriv ett tal: "))
y = float(input("skriv ett till tal: "))
print(float(x))
print(int(y))
print("Det som händer är att int till float omvandlar talet till ett decimaltal. När man omvandlar från float till int blir decimaltalet till ett heltal.")